apiVersion: v1
kind: Service
metadata:
  name: spring-boot-mongo
spec:
  selector:
    app.kubernetes.io/name: spring-boot-mongo
  ports:
    - name: http-web
      protocol: TCP
      port: 80
      targetPort: http-web-svc